Dtek\SocialProjectBundle\Entity\News:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: text
        content:
            type: text
        date:
            type: text
    lifecycleCallbacks: {  }
