publication:
    pattern:  /
    defaults: { _controller: "SocialProjectBundle:Publication:index" }

publication_show:
    pattern:  /{id}/show
    defaults: { _controller: "SocialProjectBundle:Publication:show" }

publication_new:
    pattern:  /new
    defaults: { _controller: "SocialProjectBundle:Publication:new" }

publication_create:
    pattern:  /create
    defaults: { _controller: "SocialProjectBundle:Publication:create" }
    requirements: { _method: post }

publication_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SocialProjectBundle:Publication:edit" }

publication_update:
    pattern:  /{id}/update
    defaults: { _controller: "SocialProjectBundle:Publication:update" }
    requirements: { _method: post|put }

publication_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SocialProjectBundle:Publication:delete" }
    requirements: { _method: post|delete }
