parameters:
#    social_project.example.class: Dtek\SocialProjectBundle\Example

services:
#    social_project.example:
#        class: %social_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
